//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class database : DbContext
    {
        public database()
            : base("name=database")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbl_base> tbl_base { get; set; }
        public virtual DbSet<tbl_logininformation> tbl_logininformation { get; set; }
        public virtual DbSet<tbl_sensorinformation> tbl_sensorinformation { get; set; }
        public virtual DbSet<tbl_sensors> tbl_sensors { get; set; }
        public virtual DbSet<tbl_types> tbl_types { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_setting> tbl_setting { get; set; }
    }
}
