//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sensorinformation
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int SensorID { get; set; }
        public int BaseID_ago { get; set; }
        public int BaseID_new { get; set; }
        public int TypeID_ago { get; set; }
        public int TypeID_new { get; set; }
        public double x_ago { get; set; }
        public double x_new { get; set; }
        public double y_ago { get; set; }
        public double y_new { get; set; }
        public string State_ago { get; set; }
        public string State_new { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual tbl_sensors tbl_sensors { get; set; }
        public virtual tbl_users tbl_users { get; set; }
    }
}
