//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_logininformation
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
    
        public virtual tbl_users tbl_users { get; set; }
    }
}
